# Generated by Django 5.2.1 on 2026-08-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='季語')),
                ('season', models.CharField(choices=[('spring', '春'), ('summer', '夏'), ('autumn', '秋'), ('winter', '冬')], max_length=6, verbose_name='季節')),
                ('genre', models.CharField(choices=[('plant', '植物'), ('animal', '動物'), ('event', '行事'), ('weather', '気象')], max_length=10, verbose_name='お題ジャンル')),
            ],
        ),
    ]
