# Generated by Django 5.2.1 (recreated)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haiku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haiku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='五七五')),
                ('author_name', models.CharField(max_length=20, verbose_name='投稿者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('kigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='haiku.kigo', verbose_name='季語')),
            ],
        ),
    ]
