# Generated by Django 5.2.1 on 2026-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haiku', '0002_haiku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muchaburi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50, verbose_name='無茶ぶり')),
            ],
        ),
    ]
